name: Publish Package
on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/andrewhakimian
    
    - name: Display package.json content
      run: cat package.json
      working-directory: /.github/actions/local-action/package.json
      
    - name: Install dependencies
      run: npm ci
      working-directory: /.github/actions/local-action/package.json
      
    - name: Build
      run: npm run build
      working-directory: /.github/actions/local-action/package.json
      
    - name: Publish
      run: npm publish
      working-directory: /.github/actions/local-action/package.json
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
